### PR TITLE
Add KAN to pyLOM.NN module

### LINKED ISSUE #60: Integrating KAN on pyLOM
This issue has as goal integrating the Kolmogorov-Arnold Networks (KAN) [https://arxiv.org/abs/2404.19756](https://arxiv.org/abs/2404.19756) on the NN module from pyLOM. It will follow the pipeline model interface.

### PR DESCRIPTION
**Pull request by DavidRamosArchilla**
KAN is adapted to the pipeline and can be optimized with optuna. Closes #60

### CODE REVIEW

**Comment by ArnauMiro** [comment]
@DavidRamosArchilla  can you add the example with the XFOIL data following the example of the MLP? I will then follow up checking the algorithms and adding their corresponding part on the testsuite.

**Review by ArnauMiro — CHANGES_REQUESTED** [review]
Waiting to finalize examples

**Comment by DavidRamosArchilla** [comment]
> @DavidRamosArchilla can you add the example with the XFOIL data following the example of the MLP? I will then follow up checking the algorithms and adding their corresponding part on the testsuite.

Okay, i add it now

**Comment by DavidRamosArchilla** [comment]
@ArnauMiro I've already added the example with the XFOIL data for the KAN. 
Also, I noticed that the example of the MLP with that same that is wrong because  the parameter snapshots_by_column on the dataset was set to false when I used the csv version of the dataset, but now that the format is h5, that parameter should be true. I've changed that too in the example and in the testsuite case

**Review by ArnauMiro — APPROVED** [review]

**Pull request merged**
